# Generated by Django 5.0.14 on 2026-07-06 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recorded_at", models.DateTimeField()),
                ("weight_kg", models.FloatField()),
                ("body_fat_pct", models.FloatField(blank=True, null=True)),
                ("muscle_mass_kg", models.FloatField(blank=True, null=True)),
                ("bone_mass_kg", models.FloatField(blank=True, null=True)),
                ("bmi", models.FloatField(blank=True, null=True)),
                ("raw", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("total_steps", models.PositiveIntegerField(blank=True, null=True)),
                ("resting_hr", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("total_calories", models.PositiveIntegerField(blank=True, null=True)),
                ("active_calories", models.PositiveIntegerField(blank=True, null=True)),
                ("sleep_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("stress_avg", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "body_battery_high",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "body_battery_low",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("hrv_status", models.CharField(blank=True, max_length=32)),
                ("hrv_last_night_avg", models.FloatField(blank=True, null=True)),
                (
                    "training_readiness_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("vo2max_running", models.FloatField(blank=True, null=True)),
                ("vo2max_cycling", models.FloatField(blank=True, null=True)),
                ("raw", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddConstraint(
            model_name="bodycomposition",
            constraint=models.UniqueConstraint(
                fields=("user", "recorded_at"), name="uniq_user_weighin"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailystats",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="uniq_user_date_stats"
            ),
        ),
    ]
