# Generated by Django 5.0.14 on 2026-07-06 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("garmin_activity_id", models.BigIntegerField()),
                ("activity_type", models.CharField(max_length=64)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("start_time_local", models.DateTimeField()),
                ("start_time_gmt", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("distance_m", models.FloatField(blank=True, null=True)),
                ("elevation_gain_m", models.FloatField(blank=True, null=True)),
                ("average_hr", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_hr", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("calories", models.PositiveIntegerField(blank=True, null=True)),
                ("raw_summary", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time_local"],
                "indexes": [
                    models.Index(
                        fields=["user", "start_time_local"],
                        name="activities__user_id_013c73_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.UniqueConstraint(
                fields=("user", "garmin_activity_id"), name="uniq_user_activity"
            ),
        ),
    ]
