# Generated by Django 5.0.14 on 2026-07-06 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("garmin_gear_uuid", models.CharField(blank=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("gear_type", models.CharField(blank=True, max_length=64)),
                ("is_retired", models.BooleanField(default=False)),
                ("total_distance_m", models.FloatField(default=0)),
                ("total_duration_seconds", models.FloatField(default=0)),
                ("raw", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GearMaintenanceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("performed_at", models.DateField()),
                ("distance_at_service_m", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "gear",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_entries",
                        to="gear.gear",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="gear",
            constraint=models.UniqueConstraint(
                fields=("user", "garmin_gear_uuid"), name="uniq_user_gear_uuid"
            ),
        ),
    ]
